config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  root to: 'home#index'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags
  has_one_attached :image

  validates :description, :image, presence: true
  after_commit :create_hash_tags, on: :create

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    redirect_back fallback_location: root_path, alert: 'El usuario no existe'
  end

  protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :website, :bio, :email, :phone, :gender])
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(5)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show, :destroy]

  def new
    @post = Post.new
  end

  def show

  end

  def create
    @post = @user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html {redirect_to root_path, notice: "Se ha creado el post"}
      else
        format.html {render :new, alert: "Error inesperado, intente nuevamente"}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @post.destroy
        format.html {redirect_to user_path(@user), notice: 'Post Eliminado'}
      else
        format.html {redirect_to user_path(@user), alert: 'No se pudo eliminar el post, intente nuevamente'}
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:description, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name: query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  before_action :check_current_user, only:[:edit]


  def show
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user), notice: '¡ Perfil actualizado correctamente !'
    else
      render :edit, alert: '¡ Error al actualizar, intente nuevamente !'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_current_user
    if user_signed_in?
      if current_user.id != @user.id
        redirect_back fallback_location: edit_user_path(current_user), alert: 'No puedes acceder a otro perfil para editarlo'
      end
    else
      redirect_back fallback_location: root_path, alert: 'Se ha presentado un error, intente nuevamente'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alerts/_alert.html.haml
.alert.alert-danger.alert-dismissible.fade.show.text-center
  = flash[:alert]
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/alerts/_notice.html.haml
.alert.alert-success.alert-dismissible.fade.show.text-center
  = notice
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/home/index.html.haml
.container
  .posts
    - @posts.each do |post|
      .section.post
        .user
          .avatar
            - if post.user.avatar.attached?
              = link_to user_path(post.user) do
                = image_tag (post.user.avatar), class: ''
            - else
              = image_tag ('hombre.svg')
          = link_to post.user.username, user_path(post.user), class: 'username'
        = image_tag (post.image), class: 'main-image'
        .description
          - post.description.to_s.split(' ').each do |word|
            - if word.start_with?('#')
              = link_to word, search_path(query: word)
            - else
              = word
    = paginate @posts

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    %title Instagram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    -# Navigation Bar
    %nav.navbar.navbar-light.bg-light.d-flex
      .container
        .logo
          %a{href: root_path, class:'navbar-brand'}
            = fa_stacked_icon "camera inverse", base: 'circle'
            Instagram
        .m-auto.d-none.d-sm-block
          = form_with(url: search_path, method: :get, local: true, class:'form-inline search-form') do |form|
            = form.text_field :query, value:params[:query], class:'form-control mr-sm-2', placeholder:'@search', 'aria-label':'Search'
        .user-section
          %a
          - if user_signed_in?
            = link_to destroy_user_session_path, method: 'delete' do
              %i.fa.fa-compass
          %a
            %i.fa.fa-heart
          -if user_signed_in?
            = link_to user_path(current_user) do
              -# destroy_user_session_path, method: 'delete' do
              %i.fa.fa-user
          -else
            = link_to new_user_session_path do
              %i.fa.fa-sign-in

    -# Main Content
    %main
      #notice= render 'alerts/notice' if (flash[:notice])
      #error= render 'alerts/alert' if (flash[:alert])
      = yield

    -# Footer
    %footer.container.footer
      %nav.navbar.d-flex
        %ul
          %li ABOUT US
          %li SUPPORT
          %li PRESS
          %li API
          %li JOBS
          %li PRIVACY
          %li TERMS
          %li DIRECTORY
          %li PROFILES
          %li HASHTAGS
          %li LANGUAGES
      %span © 2020 INSTAGRAM

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |f|
  - if post.errors.any?
    .row.justify-content-center
      .col-md-6
        #error_explanation.alert.alert-danger.alert-dismissible.fade.show
          %h4
            = pluralize(post.errors.count, "error")
            al intentar guardar el Post:
          %ul
            - post.errors.full_messages.each do |message|
              %li= message
          %button.close{ 'data-dismiss': 'alert' }
            %span x
  .form-group
    = f.text_field :description, class: 'form-control'
  .form-group
    = f.file_field :image, class: 'form-control-file'
  .form-group
    =f.submit 'Crear Post', class: "btn btn-primary"

app/views/posts/new.html.haml
.container
  %h1 Crear un Post
  =render 'form', post: @post

app/views/posts/show.html.haml
.container
  .post-show.row
    .col-md-8
      = image_tag (@post.image), class: 'image-posts'
    .col-md-4
      .user-posts
        .avatar-posts
          -if @post.user.avatar.attached?
            = link_to user_path(@post.user) do
              = image_tag (@post.user.avatar)
        = link_to @post.user.username, user_path(@post.user), class: 'username-posts'
      .description-posts
        - @post.description.to_s.split(' ').each do |word|
          - if word.start_with?('#')
            = link_to word, search_path(query: word)
          - else
            = word
      - if user_signed_in?
        .delete
          - if @user.posts.exists?(@post.id)
            = link_to 'Eliminar', post_path(@post), method: :delete, data: {confirm: '¿Estás seguro?'}

app/views/search/index.html.haml
.container
  .search-page
    - if @posts.exists?
      %h1 Top Posts
    - else
      %h1.text-center Ooops! No se encontraron resultados ...

  .user-images
    - @posts.each do |post|
      .wrapper
        = image_tag (post.image), class: ''

app/views/users/edit.html.haml
.container
  .user-edit-page
    .actions.d-none.d-sm-block
      %nav{class:'flex-column nav-pills', role: 'tablist', 'aria-orientation': 'vertical'}
        %a{href:"#v-pills-home", class:'nav-link active', 'data-toggle': 'pill', role: 'tab', 'aria-selected': 'true'} Editar Perfil
        %a{class:'nav-link', 'data-toggle': 'pill'} Cambiar Contraseña
        %a{class:'nav-link', 'data-toggle': 'pill'} Aplicaciones y Sitios Web
        %a{class:'nav-link', 'data-toggle': 'pill'} Correo electrónico y SMS
        %a{class:'nav-link', 'data-toggle': 'pill'} Administrar contactos
        %a{class:'nav-link', 'data-toggle': 'pill'} Privacidad y Seguridad
    .details.tab-content
      %div{class:'tab-pane fade show active', id:'v-pills-home', role:'tabpanel', 'aria-labelledby': 'v-pills-home-tab'}
        =form_with(model: current_user, local: true, class:'form-horizontal form-edit-user') do |f|
          .form-group
            .row
              .col-sm-3.col-image-profile.col-form-label
                - if current_user.avatar.attached?
                  = image_tag (current_user.avatar), class: 'avatar'
                -else
                  = f.label :avatar
              .col-sm-9
                = f.file_field :avatar, class: 'form-control-file'
              -# .col-sm-9.col-text-profile
              -#   %p.username=current_user.username
              -#   %a{class:'change-photo', href:"#"}Cambiar foto de perfil
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :name, 'Nombre'
              .col-sm-9
                = f.text_field :name, class:'form-control'
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :username, 'Nombre de Usuario'
              .col-sm-9
                = f.text_field :username, class:'form-control'
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :website, 'Sitio Web'
              .col-sm-9
                = f.text_field :website, class:'form-control'
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :bio, 'Biografía'
              .col-sm-9
                = f.text_area :bio, class:'form-control'
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :email, 'Correo Electrónico'
              .col-sm-9
                = f.text_field :email, class:'form-control'
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :phone, 'Teléfono'
              .col-sm-9
                = f.text_field :phone, class:'form-control'
          .form-group
            .row
              .col-sm-3.col-form-label
                =f.label :gender, 'Género'
              .col-sm-9
                = f.text_field :gender, class:'form-control'
          .form-group
            .row.justify-content-center
              .col-md-6
                = f.submit "Guardar", class: 'btn btn-primary'

app/views/users/show.html.haml
.user-profile
  .container
    .profile.row.justify-content-center
      .col-sm-4.col-md-4.avatar
        .wrapper
          -if @user.avatar.attached?
            = image_tag (@user.avatar), class: ''
      .col-sm-8.col-md-8.basic-info
        .row
          %h2.username.d-none.d-sm-block=@user.username
          - if (user_signed_in?) && (current_user.id == @user.id)
            %a{href:edit_user_path(@user), class: 'edit-profile d-none d-sm-block'}
              %button Editar Perfil
        -# Inicio para mostrar este contenido al pasar al tamaño de un dispositivo celular
        .col.d-block.d-sm-none
          %h2.username=@user.username
        .col.d-block.d-sm-none.mb-3
          - if (user_signed_in?) && (current_user.id == @user.id)
            %a{href:edit_user_path(@user), class: 'edit-profile'}
              %button Editar Perfil
        -# Fin de bloque para tamaño de celular
        %ul.numbers-info.d-none.d-sm-block.d-sm-none.d-md-block
          %li
            %span=@posts.count
            Publicaciones
          %li
            %span 429
            Seguidores
          %li
            %span 956
            Seguidos
        %h2.name.d-none.d-sm-block=@user.name
        =link_to @user.website, @user.website, class: 'website d-none d-sm-block'

    -# Se muestra al pasar al tamaño de un dispositivo celular
    .row.d-block.d-sm-none
      %ul.center-ul
        %li
          %span
            %span.center-ul-data=@posts.count
            Publicaciones
        %li
          %span
            %span.center-ul-data 429
            Seguidores
        %li
          %span
            %span.center-ul-data 956
            Seguidos
    -# Fin de bloque para tamaño de celular

    .row.justify-content-center.d-none.d-sm-block
      .col-md-12.user-tabs.text-center
        %a{href:"#", class:'tab active'}
          %i.fa.fa-th
          POSTS
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-tv
          IGTV
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-bookmark
          SAVED
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-tag
          TAGGED

    -# Se muestra al pasar al tamaño de un dispositivo celular
    .row.d-block.d-sm-none
      .col-md-12.user-tabs-2.d-flex.justify-content-around
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-th
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-tv
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-bookmark
        = link_to new_user_session_path, class:'tab' do
          %i.fa.fa-tag
    -# Fin de bloque para tamaño de celular

    .row.justify-content-around.text-center
      - @posts.each do |post|
        .col-xs-4.col-sm-4.col-md-4
          = link_to post_path(post) do
            = image_tag (post.image), class: 'img-fluid gallery'